<?php
/**
 * Example included file with shortcode functionality
 */

function example_included_function() {
    return "This is from the included file!";
}

/**
 * Register the demonstration shortcode
 */
function arsol_wps_packet_example_shortcode() {
    $output = '<div class="arsol-wps-packet-example">';
    $output .= '<h3 class="included-css-class-red">Arsol WP Snippets Packet Example</h3>';
    $output .= '<p>This content is being generated by a function from an included file:</p>';
    $output .= '<div class="example-output included-css-class-blue">' . example_included_function() . '</div>';
    $output .= '<p><small>This demonstrates how a packet can include its own files and provide functionality through shortcodes.</small></p>';
    $output .= '</div>';
    
    return $output;
}

// Register the shortcode
add_shortcode('arsol-wps-packet-example', 'arsol_wps_packet_example_shortcode');

add_filter('arsol_wp_snippets_css_addon_files', 'arsol_wps_packet_example_css');
function arsol_wps_packet_example_css($css_options) {
    $css_options[] = array(
        'name' => 'Example nested CSS files inside included PHP file',
        'file' => plugin_dir_url(__FILE__) . 'included-assets-folder/included-css-folder/included-asset-file.css',
        'context' => 'frontend',
        'loading_order' => 10,
        'dependencies' => array()
    );
    return $css_options;
}
