<?php
/**
 * Example included file with shortcode functionality
 */

function example_included_function() {
    return "This is from the included file!";
}

/**
 * Register the demonstration shortcode
 */
function arsol_wps_packet_example_shortcode() {
    $output = '<div class="arsol-wps-packet-example">';
    $output .= '<h3>Arsol WP Snippets Packet Example</h3>';
    $output .= '<p>This content is being generated by a function from an included file:</p>';
    $output .= '<div class="example-output">' . example_included_function() . '</div>';
    $output .= '<p><small>This demonstrates how a packet can include its own files and provide functionality through shortcodes.</small></p>';
    $output .= '</div>';
    
    return $output;
}

// Register the shortcode
add_shortcode('arsol-wps-packet-example', 'arsol_wps_packet_example_shortcode');
